### ISSUE TITLE
Change database from text to Azure MySQL (or Azure CosmosDB)

### ISSUE THREAD

**Issue by rue-glitch** [CSC207-UofT/course-project-super-turtle-hackers#11]
Storing text in databases was meant to be temporary solution; it is time to switch to Azure MySQL for more adaptability and a robust solution.

**Comment by aksh-n** [comment]
We've made progress on this. We've successfully created a course database using Azure MySQL. PRs #28 and #37 are some of the important ones among several PRs that accomplish this.

**Comment by aksh-n** [comment]
It seems that AzureMySQL makes it more difficult than necessary to store Entities with collections and user-defined entities. I will look into AzureNoSQL CosmosDB soon.

**Comment by aksh-n** [comment]
Update: successfully connected application to CosmosDB, after much troubleshooting. 
Will try to store Users soon.

**Comment by aksh-n** [comment]
Due to insufficient, inconsistent and not updated documentation for Azure CosmosDB (especially for MongoDB API), we decided to stick with Azure MySQL. #45 reverts back to using Azure MySQL.
